<template><div><p>Image having a registration form or any other form of textual user input. If the user accidentally or purposely types a space at the end of the input, other issues could follow up - double spaces, a username with spaces that does not work for login, because the user does not know.</p>
<p>We could, of course, trim every string before saving, or define it in every setter/getter. However, there is a more simple way to automatically trim all strings.</p>
<p>Using a <strong>FacesConverter</strong>, we can intercept every string input and modify it. We are using the <em>javax.faces.convert.Converter</em>-Interface that defines two methods:</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token class-name">Object</span> <span class="token function">getAsObject</span><span class="token punctuation">(</span><span class="token class-name">FacesContext</span> context<span class="token punctuation">,</span> <span class="token class-name">UIComponent</span> component<span class="token punctuation">,</span> <span class="token class-name">String</span> value<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">getAsString</span><span class="token punctuation">(</span><span class="token class-name">FacesContext</span> context<span class="token punctuation">,</span> <span class="token class-name">UIComponent</span> component<span class="token punctuation">,</span> <span class="token class-name">Object</span> value<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Using the <strong>@FacesConverter</strong>-Annotation, the converter is registered automatically. The annotation has a property named forClass, that defines the data type for which we want to use the converter. Let's define a converter for intercepting all Strings and trim them:</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">import</span> <span class="token import"><span class="token namespace">javax<span class="token punctuation">.</span>faces<span class="token punctuation">.</span>component<span class="token punctuation">.</span></span><span class="token class-name">UIComponent</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">javax<span class="token punctuation">.</span>faces<span class="token punctuation">.</span>context<span class="token punctuation">.</span></span><span class="token class-name">FacesContext</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">javax<span class="token punctuation">.</span>faces<span class="token punctuation">.</span>convert<span class="token punctuation">.</span></span><span class="token class-name">Converter</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">javax<span class="token punctuation">.</span>faces<span class="token punctuation">.</span>convert<span class="token punctuation">.</span></span><span class="token class-name">FacesConverter</span></span><span class="token punctuation">;</span>

<span class="token annotation punctuation">@FacesConverter</span><span class="token punctuation">(</span>forClass <span class="token operator">=</span> <span class="token class-name">String</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span>
<span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">StringTrimmer</span> <span class="token keyword">implements</span> <span class="token class-name">Converter</span>
<span class="token punctuation">{</span>

  <span class="token annotation punctuation">@Override</span>
  <span class="token keyword">public</span> <span class="token class-name">Object</span> <span class="token function">getAsObject</span><span class="token punctuation">(</span><span class="token class-name">FacesContext</span> context<span class="token punctuation">,</span> <span class="token class-name">UIComponent</span> component<span class="token punctuation">,</span> <span class="token class-name">String</span> value<span class="token punctuation">)</span>
  <span class="token punctuation">{</span>
    <span class="token keyword">return</span> value <span class="token operator">!=</span> <span class="token keyword">null</span> <span class="token operator">?</span> value<span class="token punctuation">.</span><span class="token function">trim</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

  <span class="token annotation punctuation">@Override</span>
  <span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">getAsString</span><span class="token punctuation">(</span><span class="token class-name">FacesContext</span> context<span class="token punctuation">,</span> <span class="token class-name">UIComponent</span> component<span class="token punctuation">,</span> <span class="token class-name">Object</span> value<span class="token punctuation">)</span>
  <span class="token punctuation">{</span>
    <span class="token keyword">return</span> value<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>That's it. By using <strong><em>forClass = String.class</em></strong>, the converter will automatically intercept any String. If we don't specify forClass, the converter will only be used when explicitly defined in the XHTML. If we want to define an alternative name for the converter, we can do so by defining the value-attribute of the FacesConverter-Annotation.</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">h:</span>inputText</span> <span class="token attr-name">value</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>#{registrationBean.username}<span class="token punctuation">"</span></span> <span class="token attr-name">required</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>true<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
   <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">f:</span>converter</span> <span class="token attr-name">converterId</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>stringTrimmer<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">h:</span>inputText</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>If you like this post, feel free to follow me or hit me up on <a href="https://twitter.com/kevcodez" target="_blank" rel="noopener noreferrer">Twitter<ExternalLinkIcon/></a>.</p>
</div></template>
