<template><div><h1 id="retry-sending-metrics-to-micrometer-in-spring-boot-on-failure" tabindex="-1"><a class="header-anchor" href="#retry-sending-metrics-to-micrometer-in-spring-boot-on-failure" aria-hidden="true">#</a> Retry sending metrics to Micrometer in Spring Boot on failure</h1>
<p><a href="https://micrometer.io/" target="_blank" rel="noopener noreferrer">Micrometer<ExternalLinkIcon/></a> allows you to instrument your JVM-based application to submit metrics.</p>
<p>Micrometer only collects the metrics and then submits it to a registry. Many differrent registries are supported, such as Elasticsearch or Prometheus.
When metrics are submitted via HTTP, no known HTTP client library like apache-httpclient or okhttp is used, but rather a simple <code v-pre>HttpUrlConnectionSender</code>-Interface.
Thus, to retry on network transmission failure, the retry logic has to be implemented by yourself.</p>
<p>You may use libraries such as <a href="https://github.com/resilience4j/resilience4j" target="_blank" rel="noopener noreferrer">resilience4j<ExternalLinkIcon/></a>.</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">private</span> <span class="token keyword">class</span> RetryHttpClient <span class="token operator">:</span> <span class="token function">HttpUrlConnectionSender</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>

    <span class="token keyword">private</span> <span class="token keyword">val</span> retryConfig <span class="token operator">=</span> RetryConfig<span class="token punctuation">.</span>custom<span class="token operator">&lt;</span>RetryConfig<span class="token operator">></span><span class="token punctuation">(</span><span class="token punctuation">)</span> 
        <span class="token punctuation">.</span><span class="token function">maxAttempts</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">waitDuration</span><span class="token punctuation">(</span>Duration<span class="token punctuation">.</span><span class="token function">ofSeconds</span><span class="token punctuation">(</span><span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">build</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    <span class="token keyword">private</span> <span class="token keyword">val</span> retry<span class="token operator">:</span> Retry <span class="token operator">=</span> Retry<span class="token punctuation">.</span><span class="token function">of</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"elasticsearch-metrics"</span></span><span class="token punctuation">,</span> retryConfig<span class="token punctuation">)</span>

    <span class="token keyword">override</span> <span class="token keyword">fun</span> <span class="token function">send</span><span class="token punctuation">(</span>request<span class="token operator">:</span> HttpSender<span class="token punctuation">.</span>Request<span class="token punctuation">)</span><span class="token operator">:</span> HttpSender<span class="token punctuation">.</span><span class="token function">Response</span> <span class="token punctuation">{</span>
        <span class="token keyword">val</span> retryableSupplier <span class="token operator">=</span> Retry<span class="token punctuation">.</span><span class="token function">decorateCheckedSupplier</span><span class="token punctuation">(</span>retry<span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token keyword">super</span><span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span>request<span class="token punctuation">)</span> <span class="token punctuation">}</span>
        <span class="token keyword">return</span> Try<span class="token punctuation">.</span><span class="token function">of</span><span class="token punctuation">(</span>retryableSupplier<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Using this RetryHttpClient, the submission of metrics is retried up to three times. On each failure, the client waits 5 seconds before trying again.</p>
<p>To use the custom RetryHttpClient in your Spring Boot application, you need to overwrite the <code v-pre>ElasticMeterRegistry</code> that is provided by micrometer by default.</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token annotation builtin">@Bean</span>
<span class="token annotation builtin">@ConditionalOnProperty</span><span class="token punctuation">(</span>prefix <span class="token operator">=</span> <span class="token string-literal singleline"><span class="token string">"management.metrics.export.elastic"</span></span><span class="token punctuation">,</span> name <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string-literal singleline"><span class="token string">"enabled"</span></span><span class="token punctuation">]</span><span class="token punctuation">,</span> havingValue <span class="token operator">=</span> <span class="token string-literal singleline"><span class="token string">"true"</span></span><span class="token punctuation">,</span> matchIfMissing <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">)</span> 
<span class="token keyword">fun</span> <span class="token function">elasticMeterRegistry</span><span class="token punctuation">(</span>elasticConfig<span class="token operator">:</span> ElasticConfig<span class="token punctuation">)</span><span class="token operator">:</span> ElasticMeterRegistry <span class="token punctuation">{</span> 
    <span class="token keyword">return</span> ElasticMeterRegistry<span class="token punctuation">.</span><span class="token function">builder</span><span class="token punctuation">(</span>elasticConfig<span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">clock</span><span class="token punctuation">(</span>Clock<span class="token punctuation">.</span>SYSTEM<span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">httpClient</span><span class="token punctuation">(</span><span class="token function">RetryHttpClient</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">build</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>The <code v-pre>ConditionalOnProperty</code> prevents the bean being initialised in an environment, where micrometer is not supported, i.e. when running unit tests.</p>
<p>The <code v-pre>ElasticConfig</code> class is provided by micrometer.</p>
</div></template>
