<template><div><p>Sending mails with Java is pretty simple using the Apache Commons Mail Library. Start by adding the commons-email dependency to your poject</p>
<div class="language-xml ext-xml line-numbers-mode"><pre v-pre class="language-xml"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>dependency</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>groupId</span><span class="token punctuation">></span></span>org.apache.commons<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>groupId</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>artifactId</span><span class="token punctuation">></span></span>commons-email<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>artifactId</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>version</span><span class="token punctuation">></span></span>1.4<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>version</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>dependency</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="sending-plain-text-emails" tabindex="-1"><a class="header-anchor" href="#sending-plain-text-emails" aria-hidden="true">#</a> Sending plain-text Emails</h2>
<p>Here's a code sample for sending a plain-text email using the GMail SMTP server. Settings the debug mode to true, we get a lot of output on what happens.</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code>  <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span> <span class="token class-name">String</span> SMTP\_HOST <span class="token operator">=</span> <span class="token string">"smtp.gmail.com"</span><span class="token punctuation">;</span>
  <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span> <span class="token keyword">int</span> SMTP\_PORT <span class="token operator">=</span> <span class="token number">465</span><span class="token punctuation">;</span>
  
  <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span> <span class="token class-name">String</span> USERNAME <span class="token operator">=</span> <span class="token string">"user@gmail.com"</span><span class="token punctuation">;</span>
  <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span> <span class="token class-name">String</span> PASSWORD <span class="token operator">=</span> <span class="token string">"pw"</span><span class="token punctuation">;</span>

  <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token keyword">void</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token class-name">String</span>\<span class="token punctuation">[</span>\<span class="token punctuation">]</span> args<span class="token punctuation">)</span> <span class="token keyword">throws</span> <span class="token class-name">EmailException</span>
  <span class="token punctuation">{</span>
    <span class="token class-name">SimpleEmail</span> email <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">SimpleEmail</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    email<span class="token punctuation">.</span><span class="token function">setHostName</span><span class="token punctuation">(</span>SMTP\_HOST<span class="token punctuation">)</span><span class="token punctuation">;</span>
    email<span class="token punctuation">.</span><span class="token function">setAuthentication</span><span class="token punctuation">(</span>USERNAME<span class="token punctuation">,</span> PASSWORD<span class="token punctuation">)</span><span class="token punctuation">;</span>
    email<span class="token punctuation">.</span><span class="token function">setDebug</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    email<span class="token punctuation">.</span><span class="token function">setSmtpPort</span><span class="token punctuation">(</span>SMTP\_PORT<span class="token punctuation">)</span><span class="token punctuation">;</span>
    email<span class="token punctuation">.</span><span class="token function">setSSLOnConnect</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    email<span class="token punctuation">.</span><span class="token function">addTo</span><span class="token punctuation">(</span><span class="token string">"empfaenger@domain.de"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    email<span class="token punctuation">.</span><span class="token function">setFrom</span><span class="token punctuation">(</span>USERNAME<span class="token punctuation">,</span> <span class="token string">"Name of thesender"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    email<span class="token punctuation">.</span><span class="token function">setSubject</span><span class="token punctuation">(</span><span class="token string">"Test message"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    email<span class="token punctuation">.</span><span class="token function">setMsg</span><span class="token punctuation">(</span><span class="token string">"Hey, this is a simple text"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    email<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="sending-emails-with-attachments" tabindex="-1"><a class="header-anchor" href="#sending-emails-with-attachments" aria-hidden="true">#</a> Sending emails with attachments</h2>
<p>For sending emails with attachments, we cannot use the <em>SimpleEmail class</em>. We need to use the <strong>MultiPartEmail</strong> class.</p>
<p>There are multiple ways to add an attachment to a mail. One example:</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">EmailAttachment</span> attachment <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">EmailAttachment</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
attachment<span class="token punctuation">.</span><span class="token function">setPath</span><span class="token punctuation">(</span><span class="token string">"mypictures/john.jpg"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
attachment<span class="token punctuation">.</span><span class="token function">setDisposition</span><span class="token punctuation">(</span><span class="token class-name">EmailAttachment</span><span class="token punctuation">.</span>ATTACHMENT<span class="token punctuation">)</span><span class="token punctuation">;</span>
attachment<span class="token punctuation">.</span><span class="token function">setDescription</span><span class="token punctuation">(</span><span class="token string">"Picture of John"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
attachment<span class="token punctuation">.</span><span class="token function">setName</span><span class="token punctuation">(</span><span class="token string">"John"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

email<span class="token punctuation">.</span><span class="token function">attach</span><span class="token punctuation">(</span>attachment<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>or even easier:</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code>email<span class="token punctuation">.</span><span class="token function">attach</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">File</span><span class="token punctuation">(</span><span class="token string">"C:/testfile.txt"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>You can also provide an URL to a file, that will be downloaded and attached:</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code>mail<span class="token punctuation">.</span><span class="token function">attach</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">URL</span><span class="token punctuation">(</span><span class="token string">"http://urltofile.extension"</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">"Name"</span><span class="token punctuation">,</span> <span class="token string">"Description"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>An entire code sample for sending a mail with an attachment may look like this:</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">MultiPartEmail</span> email <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">MultiPartEmail</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setHostName</span><span class="token punctuation">(</span>SMTP\_HOST<span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setAuthentication</span><span class="token punctuation">(</span>USERNAME<span class="token punctuation">,</span> PASSWORD<span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setDebug</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setSmtpPort</span><span class="token punctuation">(</span>SMTP\_PORT<span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setSSLOnConnect</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    
email<span class="token punctuation">.</span><span class="token function">attach</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">File</span><span class="token punctuation">(</span><span class="token string">"C:/testfile.txt"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

email<span class="token punctuation">.</span><span class="token function">addTo</span><span class="token punctuation">(</span><span class="token string">"empfaenger@domain.de"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

email<span class="token punctuation">.</span><span class="token function">setFrom</span><span class="token punctuation">(</span>USERNAME<span class="token punctuation">,</span> <span class="token string">"Sender name"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setSubject</span><span class="token punctuation">(</span><span class="token string">"Test message with attachment"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setMsg</span><span class="token punctuation">(</span><span class="token string">"Hey there, here is my file"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="sending-emails-with-html" tabindex="-1"><a class="header-anchor" href="#sending-emails-with-html" aria-hidden="true">#</a> Sending emails with HTML</h2>
<p>To send emails with HTML, you need to use the <em>HtmlEmail</em> class.</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">HtmlEmail</span> email <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">HtmlEmail</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setHostName</span><span class="token punctuation">(</span>SMTP\_HOST<span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setAuthentication</span><span class="token punctuation">(</span>USERNAME<span class="token punctuation">,</span> PASSWORD<span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setDebug</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setSmtpPort</span><span class="token punctuation">(</span>SMTP\_PORT<span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setSSLOnConnect</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

email<span class="token punctuation">.</span><span class="token function">setHtmlMsg</span><span class="token punctuation">(</span><span class="token string">"&lt;html>Test message with &lt;b>HTML&lt;/b>&lt;/html>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Just in case HTML is unsupported</span>
email<span class="token punctuation">.</span><span class="token function">setTextMsg</span><span class="token punctuation">(</span><span class="token string">"Dein E-Mail-Client unterstützt kein HTML."</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

email<span class="token punctuation">.</span><span class="token function">addTo</span><span class="token punctuation">(</span><span class="token string">"recipient@domain.de"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setFrom</span><span class="token punctuation">(</span>USERNAME<span class="token punctuation">,</span> <span class="token string">"Sender"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">setSubject</span><span class="token punctuation">(</span><span class="token string">"Test message with HTML"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
email<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>If you like this post, feel free to follow me or hit me up on <a href="https://twitter.com/kevcodez" target="_blank" rel="noopener noreferrer">Twitter<ExternalLinkIcon/></a>.</p>
</div></template>
