<template><div><h2 id="foreword" tabindex="-1"><a class="header-anchor" href="#foreword" aria-hidden="true">#</a> Foreword</h2>
<p>In this Amazon Simple Storage Service Tutorial I'd like to give you a first introduction into S3, it's registration and code samples to upload and delete files.</p>
<h2 id="introduction-what-is-amazon-simple-storage-service" tabindex="-1"><a class="header-anchor" href="#introduction-what-is-amazon-simple-storage-service" aria-hidden="true">#</a> Introduction - What is Amazon Simple Storage Service</h2>
<p>The Amazon Simple Storage Service (in short S3) is a web service from Amazon - Amazon offers a bunch of web services under <a href="https://aws.amazon.com/de/" target="_blank" rel="noopener noreferrer">Amazon AWS (Amazon Web Services)<ExternalLinkIcon/></a>. S3 is a cloud storage that scales to your needs, you don't have to worry to be out of storage space. S3 is used by many companies, like Netflix and Pinterest. You pay as you go, meaning you only pay for what you really use. Take a look at this neat introduction video:</p>
<iframe width="556" height="313" src="https://www.youtube.com/embed/rKpKHulqYOQ" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
<h2 id="what-does-the-amazon-simple-storage-service-cost" tabindex="-1"><a class="header-anchor" href="#what-does-the-amazon-simple-storage-service-cost" aria-hidden="true">#</a> What does the Amazon Simple Storage Service cost</h2>
<p>The free contigent contains <strong>5 GB Storage</strong>, <strong>20 000 GET</strong>-Request and <strong>2000 PUT</strong>-Requests. Check out the full price list at <a href="https://aws.amazon.com/de/s3/pricing/" target="_blank" rel="noopener noreferrer">Amazon S3 - Preisliste<ExternalLinkIcon/></a>. The prices depend on the selected region. You may choose any region.</p>
<h2 id="setup-amazon-simple-storage-service" tabindex="-1"><a class="header-anchor" href="#setup-amazon-simple-storage-service" aria-hidden="true">#</a> Setup Amazon Simple Storage Service</h2>
<p>First, you have to register for <a href="https://aws.amazon.com/de/" target="_blank" rel="noopener noreferrer">Amazon Web Services - AWS<ExternalLinkIcon/></a>. After registering successfully, you should be able to login to the AWS management console. All services should be listed there. Go to <strong>Storage &amp; Content Delivery</strong> and select <strong>S3 - Scalable Storage in a Cloud</strong>.</p>
<p>You may now create buckets in the S3 management console. A bucket is a container für any objects, that you want to store in S3. Multiple buckets for multiple projects can be created. If you want to upload or delete files, you always specify a bucket. Let's start by creating a new bucket:</p>
<p><a href="./s3_create_bucket.png">Amazon S3 - Bucket erstellen</a></p>
<p>The S3 management console can be used to upload files, however, we want to do it via Code 😉</p>
<h2 id="generate-access-key-and-private-key" tabindex="-1"><a class="header-anchor" href="#generate-access-key-and-private-key" aria-hidden="true">#</a> Generate Access-Key and Private-Key</h2>
<p>To publicly access the bucket (via Code), we need to generate a private and public key. Click on your account name -&gt; _Security Credentials -&gt; _Tab <em>Access Keys (Access Key ID and Secret Access Key)</em>. Simply hit <em>Create New Access Key</em>. <strong>Important:</strong> Write down your private key - you cannt view it again. If you loose your private key, you have to generate a new key pair and delete the old one.</p>
<p><a href="./s3_create_access_key.png">Amazon S3 - Keys erstellen</a></p>
<h2 id="upload-retreive-and-delete-and-s3-dateien-hochladen-loschen-und-abfragen-mit-java" tabindex="-1"><a class="header-anchor" href="#upload-retreive-and-delete-and-s3-dateien-hochladen-loschen-und-abfragen-mit-java" aria-hidden="true">#</a> Upload, retreive and delete and S3 Dateien hochladen, löschen und abfragen mit Java</h2>
<p>AWS offers a Java SDK at the following GAV-Coodinates:</p>
<div class="language-xml ext-xml line-numbers-mode"><pre v-pre class="language-xml"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>dependency</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>groupId</span><span class="token punctuation">></span></span>com.amazonaws<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>groupId</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>artifactId</span><span class="token punctuation">></span></span>aws-java-sdk<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>artifactId</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>version</span><span class="token punctuation">></span></span>1.10.3<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>version</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>dependency</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>I wrote a small client that lets you upload, retreive and delete files. The AmazonClient is an Enum with a single type (see <RouterLink to="/posts/2015-06-29-java-singleton-pattern/">Java Singleton Pattern - Enum</RouterLink>) - ensuring that there is only a single instance. The com.amazonaws.services.s3.AmazonS3Client is initiated once (statically) with your private and public access key. We also set the region we're in- in this case Frankfurt (EU_CENTRAL_1). You have to adjust the keys.</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">import</span> <span class="token import"><span class="token namespace">java<span class="token punctuation">.</span>io<span class="token punctuation">.</span></span><span class="token class-name">File</span></span><span class="token punctuation">;</span>

<span class="token keyword">import</span> <span class="token import"><span class="token namespace">com<span class="token punctuation">.</span>amazonaws<span class="token punctuation">.</span>auth<span class="token punctuation">.</span></span><span class="token class-name">BasicAWSCredentials</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">com<span class="token punctuation">.</span>amazonaws<span class="token punctuation">.</span>regions<span class="token punctuation">.</span></span><span class="token class-name">Region</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">com<span class="token punctuation">.</span>amazonaws<span class="token punctuation">.</span>regions<span class="token punctuation">.</span></span><span class="token class-name">Regions</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">com<span class="token punctuation">.</span>amazonaws<span class="token punctuation">.</span>services<span class="token punctuation">.</span>s3<span class="token punctuation">.</span></span><span class="token class-name">AmazonS3</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">com<span class="token punctuation">.</span>amazonaws<span class="token punctuation">.</span>services<span class="token punctuation">.</span>s3<span class="token punctuation">.</span></span><span class="token class-name">AmazonS3Client</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">com<span class="token punctuation">.</span>amazonaws<span class="token punctuation">.</span>services<span class="token punctuation">.</span>s3<span class="token punctuation">.</span>model<span class="token punctuation">.</span></span><span class="token class-name">DeleteObjectRequest</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">com<span class="token punctuation">.</span>amazonaws<span class="token punctuation">.</span>services<span class="token punctuation">.</span>s3<span class="token punctuation">.</span>model<span class="token punctuation">.</span></span><span class="token class-name">GetObjectRequest</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">com<span class="token punctuation">.</span>amazonaws<span class="token punctuation">.</span>services<span class="token punctuation">.</span>s3<span class="token punctuation">.</span>model<span class="token punctuation">.</span></span><span class="token class-name">ObjectMetadata</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">com<span class="token punctuation">.</span>amazonaws<span class="token punctuation">.</span>services<span class="token punctuation">.</span>s3<span class="token punctuation">.</span>model<span class="token punctuation">.</span></span><span class="token class-name">PutObjectRequest</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">com<span class="token punctuation">.</span>amazonaws<span class="token punctuation">.</span>services<span class="token punctuation">.</span>s3<span class="token punctuation">.</span>model<span class="token punctuation">.</span></span><span class="token class-name">S3Object</span></span><span class="token punctuation">;</span>

<span class="token keyword">public</span> <span class="token keyword">enum</span> <span class="token class-name">AmazonClient</span>
<span class="token punctuation">{</span>

  INSTANCE<span class="token punctuation">;</span>

 
  <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span> <span class="token class-name">String</span> ACCESS\_KEY <span class="token operator">=</span> <span class="token string">"accessKey"</span><span class="token punctuation">;</span>
  
  <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span> <span class="token class-name">String</span> SECRET\_KEY <span class="token operator">=</span> <span class="token string">"secretKey"</span><span class="token punctuation">;</span>

  <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span> <span class="token class-name">AmazonS3</span> amazonClient<span class="token punctuation">;</span>

  <span class="token keyword">static</span>
  <span class="token punctuation">{</span>
    amazonClient <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">AmazonS3Client</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">BasicAWSCredentials</span><span class="token punctuation">(</span>ACCESS\_KEY<span class="token punctuation">,</span> SECRET\_KEY<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    amazonClient<span class="token punctuation">.</span><span class="token function">setRegion</span><span class="token punctuation">(</span><span class="token class-name">Region</span><span class="token punctuation">.</span><span class="token function">getRegion</span><span class="token punctuation">(</span><span class="token class-name">Regions</span><span class="token punctuation">.</span>EU\_CENTRAL\_1<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

  <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">uploadFile</span><span class="token punctuation">(</span><span class="token class-name">String</span> bucketName<span class="token punctuation">,</span> <span class="token class-name">String</span> key<span class="token punctuation">,</span> <span class="token class-name">File</span> file<span class="token punctuation">)</span>
  <span class="token punctuation">{</span>
    <span class="token function">uploadFile</span><span class="token punctuation">(</span>bucketName<span class="token punctuation">,</span> key<span class="token punctuation">,</span> file<span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

  <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">uploadFile</span><span class="token punctuation">(</span><span class="token class-name">String</span> bucketName<span class="token punctuation">,</span> <span class="token class-name">String</span> key<span class="token punctuation">,</span> <span class="token class-name">File</span> file<span class="token punctuation">,</span> <span class="token class-name">ObjectMetadata</span> customMetadata<span class="token punctuation">)</span>
  <span class="token punctuation">{</span>
    <span class="token class-name">PutObjectRequest</span> putObjectRequest <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">PutObjectRequest</span><span class="token punctuation">(</span>bucketName<span class="token punctuation">,</span> key<span class="token punctuation">,</span> file<span class="token punctuation">)</span><span class="token punctuation">;</span>
    putObjectRequest<span class="token punctuation">.</span><span class="token function">setMetadata</span><span class="token punctuation">(</span>customMetadata<span class="token punctuation">)</span><span class="token punctuation">;</span>
    amazonClient<span class="token punctuation">.</span><span class="token function">putObject</span><span class="token punctuation">(</span>putObjectRequest<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

 
  <span class="token keyword">public</span> <span class="token class-name">S3Object</span> <span class="token function">getFile</span><span class="token punctuation">(</span><span class="token class-name">String</span> bucketName<span class="token punctuation">,</span> <span class="token class-name">String</span> key<span class="token punctuation">)</span>
  <span class="token punctuation">{</span>
    <span class="token keyword">return</span> amazonClient<span class="token punctuation">.</span><span class="token function">getObject</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">GetObjectRequest</span><span class="token punctuation">(</span>bucketName<span class="token punctuation">,</span> key<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

  <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">deleteFile</span><span class="token punctuation">(</span><span class="token class-name">String</span> bucketName<span class="token punctuation">,</span> <span class="token class-name">String</span> key<span class="token punctuation">)</span>
  <span class="token punctuation">{</span>
    amazonClient<span class="token punctuation">.</span><span class="token function">deleteObject</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">DeleteObjectRequest</span><span class="token punctuation">(</span>bucketName<span class="token punctuation">,</span> key<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>To test the class, let's use our previously created bucket.</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">import</span> <span class="token import"><span class="token namespace">java<span class="token punctuation">.</span>io<span class="token punctuation">.</span></span><span class="token class-name">File</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">java<span class="token punctuation">.</span>io<span class="token punctuation">.</span></span><span class="token class-name">IOException</span></span><span class="token punctuation">;</span>

<span class="token keyword">import</span> <span class="token import"><span class="token namespace">com<span class="token punctuation">.</span>amazonaws<span class="token punctuation">.</span>services<span class="token punctuation">.</span>s3<span class="token punctuation">.</span>model<span class="token punctuation">.</span></span><span class="token class-name">AmazonS3Exception</span></span><span class="token punctuation">;</span>

<span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">S3UploadFile</span>
<span class="token punctuation">{</span>

  <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span> <span class="token class-name">String</span> BUCKET\_NAME <span class="token operator">=</span> <span class="token string">"kevcodez"</span><span class="token punctuation">;</span>

  <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token keyword">void</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token class-name">String</span>\<span class="token punctuation">[</span>\<span class="token punctuation">]</span> args<span class="token punctuation">)</span> <span class="token keyword">throws</span> <span class="token class-name">IOException</span>
  <span class="token punctuation">{</span>
    <span class="token class-name">File</span> file <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">File</span><span class="token punctuation">(</span><span class="token string">"C:/testfile.txt"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token class-name">String</span> filename <span class="token operator">=</span> <span class="token string">"testfile.txt"</span><span class="token punctuation">;</span>

    <span class="token comment">// Upload file</span>
    <span class="token class-name">AmazonClient</span><span class="token punctuation">.</span>INSTANCE<span class="token punctuation">.</span><span class="token function">uploadFile</span><span class="token punctuation">(</span>BUCKET\_NAME<span class="token punctuation">,</span> filename<span class="token punctuation">,</span> file<span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token comment">// Get file</span>
    <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token class-name">AmazonClient</span><span class="token punctuation">.</span>INSTANCE<span class="token punctuation">.</span><span class="token function">getFile</span><span class="token punctuation">(</span>BUCKET\_NAME<span class="token punctuation">,</span> filename<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token comment">// Delete file</span>
    <span class="token class-name">AmazonClient</span><span class="token punctuation">.</span>INSTANCE<span class="token punctuation">.</span><span class="token function">deleteFile</span><span class="token punctuation">(</span>BUCKET\_NAME<span class="token punctuation">,</span> filename<span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">try</span>
    <span class="token punctuation">{</span>
      <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token class-name">AmazonClient</span><span class="token punctuation">.</span>INSTANCE<span class="token punctuation">.</span><span class="token function">getFile</span><span class="token punctuation">(</span>BUCKET\_NAME<span class="token punctuation">,</span> filename<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">catch</span> <span class="token punctuation">(</span><span class="token class-name">AmazonS3Exception</span> ex<span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
      <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"Key not found - as expected after deletion"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>

<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="add-metadata-to-your-files" tabindex="-1"><a class="header-anchor" href="#add-metadata-to-your-files" aria-hidden="true">#</a> Add Metadata to your files</h2>
<p>Within the AmazonClient-Class, the uploadFile() method allows passing metadata from type ObjectMetadata. You can define metadata, like cacheControl. By editing cacheControl, we can define the time to cache the file, for example in a browser. Using <strong>&quot;max-age: 600&quot;</strong>, the file will be cached for 10 minutes.</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">ObjectMetadata</span> metadata <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ObjectMetadata</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
metadata<span class="token punctuation">.</span><span class="token function">setCacheControl</span><span class="token punctuation">(</span><span class="token string">"max-age: 600"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token class-name">AmazonClient</span><span class="token punctuation">.</span>INSTANCE<span class="token punctuation">.</span><span class="token function">uploadFile</span><span class="token punctuation">(</span>BUCKET\_NAME<span class="token punctuation">,</span> filename<span class="token punctuation">,</span> file<span class="token punctuation">,</span> metadata<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="makes-files-publicly-accessible" tabindex="-1"><a class="header-anchor" href="#makes-files-publicly-accessible" aria-hidden="true">#</a> Makes files publicly accessible</h2>
<p>By default, when uploading a file to your bucket, it is not publicly accessible. You can only access the file using a special link (contains a unique key).  To make every file you upload public, we have to create a new bucket policy.</p>
<p>Go to <strong>S3 Management Console</strong> and <em>Rightclick your bucket</em>-&gt; <strong>Properties</strong>. Under <strong>Permissions</strong> click <strong>Add bucket policy</strong>.</p>
<p><a href="./s3_add_bucket_policy.png">Amazon S3 - Bucket Permissions</a></p>
<p>Enter the following policy:</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code><span class="token punctuation">{</span>
  <span class="token property">"Version"</span><span class="token operator">:</span> <span class="token string">"2008-10-17"</span><span class="token punctuation">,</span>
  <span class="token property">"Statement"</span><span class="token operator">:</span> \<span class="token punctuation">[</span><span class="token punctuation">{</span>
    <span class="token property">"Sid"</span><span class="token operator">:</span> <span class="token string">"AllowPublicRead"</span><span class="token punctuation">,</span>
    <span class="token property">"Effect"</span><span class="token operator">:</span> <span class="token string">"Allow"</span><span class="token punctuation">,</span>
    <span class="token property">"Principal"</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token property">"AWS"</span><span class="token operator">:</span> <span class="token string">"\*"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token property">"Action"</span><span class="token operator">:</span> \<span class="token punctuation">[</span><span class="token string">"s3:GetObject"</span>\<span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token property">"Resource"</span><span class="token operator">:</span> \<span class="token punctuation">[</span><span class="token string">"arn:aws:s3:::kevcodez/\*"</span> \<span class="token punctuation">]</span>
  <span class="token punctuation">}</span>\<span class="token punctuation">]</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Important:</strong> Under Resource, you have to enter the name of your bucket.</p>
<p><a href="./s3_bucket_policy_editor.png">Amazon S3 - Bucket Policy Editor</a></p>
<p>If you like this post, feel free to follow me or hit me up on <a href="https://twitter.com/kevcodez" target="_blank" rel="noopener noreferrer">Twitter<ExternalLinkIcon/></a>.</p>
</div></template>
